### ISSUE TITLE
building package and missing files

### ISSUE THREAD

**Issue by oleurodecision** [theirix/conan-jsoncpp#12]
Hi,

When trying to use conan-jsoncpp, I saw that cmake config files are not packaged. It would mke the reuse of the binary packages a lot easier in some cases, as being more cmake-friendly. So : 

- is it the expected  behaviour ?
- should the files be conanly-copied when packaging ?
- or should the package step of conanfile use some cmake.install() helper ?

Can gladly submit a PR if asked

**Comment by theirix** [comment]
Hello, thanks for the idea. I checked that cmake files are not actually packaged.
Let me update the recipe soon.

**Comment by oleurodecision** [comment]
thanks !! :+1:

**Comment by theirix** [comment]
Waiting for the build...

**Comment by theirix** [comment]
Published a stable package for 1.8.4. Updated all existing binary packages and added a few more compilers.
