### ISSUE TITLE
Ability to build static with -fPIC seems to be broken.

### ISSUE THREAD

**Issue by lefticus** [theirix/conan-jsoncpp#13]
The change introduced in 641ee6898aecfa544cb1514706f456d5ab8cf69c broke my use case of needing .a that's built with -fPIC on Linux.

**Comment by lefticus** [comment]
Based on the conan documentation you need to add an option for "`fPIC`" to get the automatic behavior you are looking for: https://bincrafters.readthedocs.io/en/latest/howtos/add_fpic_option_to_recipe.html

**Comment by theirix** [comment]
Sorry, you are right. My option name differs from standard fPIC. I will return an affected line back soon.
