### ISSUE TITLE
Link error with MSVC 14

### ISSUE THREAD

**Issue by oyarsa** [theirix/conan-jsoncpp#2]
After installing the latest version by adding the package in the conanfile.txt, I tried to build a simple main.cpp (it only includes <json/json.h> and tries to declare a Json::Value inside main() ). The compiler can't find the implementation of the type, even though it seems to link correctly with the library.

The compiler output is here: http://pastebin.com/yReM30xK

My environment is Visual Studio 2015 Enterprise Update 2, Windows 10 Anniversary, CMake 3.5.0-rc1, conan 0.13.2, jsoncpp 1.7.7

**Comment by theirix** [comment]
Thank you for the report, I'll take a look.

**Comment by theirix** [comment]
It seems you are using x86_64 package while your Visual Studio project is x86 project. By the way you can check it by finding a package hash `c85f9b402dd4d46acdf074e1c63b768a41181d7a` at the [package page](https://www.conan.io/source/jsoncpp/1.7.3/theirix/stable).

Problem should be solved if you append `-s arch=x86` parameter to your `conan install` command.

**Comment by oyarsa** [comment]
Yes, changing the arch solved the problem, but what I really wanted was a x64 project. I used the default generator from cmake (which is x86), hence the conflict.

Thank you.
