### ISSUE TITLE
Support version 1.0.0

### ISSUE THREAD

**Issue by uilianries** [theirix/conan-jsoncpp#8]
Hi @theirix !

I need to use jsonrpc-cpp 0.5 for a legacy project. I just created a Conan recipe to solve it, but it uses jsoncpp 1.0.0. The newest version raises error during compile time "[JSONCPP_DEPRECATED]".

To solve cppjson, I created the support to 1.0.0. I would like to create a PR, but first would need that you create testing/1.0.0 branch.

Check my branch [here](https://github.com/uilianries/conan-jsoncpp/tree/testing/1.0.0)

Regards!

**Comment by theirix** [comment]
Hello, @uilianries !
It's always sad to use such old software as pre-C++11 jsoncpp.
I created a testing/1.0.0 branch. Please note that the package does not use bincrafters package tools so it is has more cruft.

**Comment by uilianries** [comment]
Done!

**Comment by theirix** [comment]
Published bintray package and built amost all on CI. Thanks for the PR!
